language: java
jdk:
 - oraclejdk8
script: ant create_run_jar && ant clean
notifications:
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
